name: intl_translation
version: 0.17.10+1
author: Dart Team <misc@dartlang.org>
description: >-
  Contains code to deal with internationalized/localized messages,
  date and number formatting and parsing, bi-directional text, and
  other internationalization issues.

homepage: https://github.com/dart-lang/intl_translation
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: '>=0.39.12 <1.3.1'
  args: '>=0.12.1 <2.0.1'
  dart_style: ^1.0.0
  intl: '>=0.15.3 <0.17.1'
  path: '>=0.9.0 <2.0.0'
  petitparser: ^4.0.0
dev_dependencies:
  test: ^1.16.8
